Feature/bugs fix
sliit-foss/rsvp-frontend pull request #141
Opened 2022-06-04 16:21 UTC by MadhushaPrasad

- Remove Lipsum text in login page
- Align Footer's Useful Links properly
- Change 'T' in team to 't'. ( Fill up the form and our team ... )
- Change Sign up/Login button in nav bar to match the heading in Sign up/Login page. (Ex: if login page heading in 'Login' change button text to 'Login' as well)
- Have a lighter color for footer icons

2022-06-04 16:27 UTC, sithumonline commented
@MadhushaPrasad pipeline is failed plz fix that.

2022-06-04 16:30 UTC, sithumonline commented
@MadhushaPrasad plz provide screenshot of changers.

2022-06-04 16:34 UTC, sithumonline commented
`yarn prettier --write .` plz reformat code base.

2022-06-04 16:58 UTC, nisalrenuja requested changes

2022-06-04 16:58 UTC, nisalrenuja commented on components/Login/LoginInfo.tsx
> -        <p className={paragraphClass}>
Please add content instead of removing

2022-06-04 16:58 UTC, nisalrenuja commented on components/Login/LoginInfo.tsx
> -        <p className={paragraphClass}>
Please add content Please add content instead of removing

2022-06-06 12:15 UTC, MadhushaPrasad commented
![Screenshot 2022-06-06 173216](https://user-images.githubusercontent.com/50085447/172156902-8cb04243-3562-45cd-9ea4-a1e0ea7612b5.png)
![Screenshot 2022-06-06 173316](https://user-images.githubusercontent.com/50085447/172156991-cf0cb1e3-818c-4c43-9cd5-fa2099b1c7bc.png)
![Screenshot 2022-06-06 174446](https://user-images.githubusercontent.com/50085447/172158628-2bda058b-05b8-4828-ac07-b31cd38cab21.png)

2022-06-07 06:17 UTC, MadhushaPrasad commented
![Uploading Screenshot 2022-06-07 114623.png…]()

2022-06-07 06:17 UTC, MadhushaPrasad commented
![Screenshot 2022-06-07 114623](https://user-images.githubusercontent.com/50085447/172309170-2484bf4c-eb1c-4eff-b6a3-4a1522f40fca.png)

2022-06-07 14:56 UTC, nisalrenuja approved these changes

2022-06-07 14:57 UTC, merged