Feature/events
sliit-foss/rsvp-frontend pull request #44
Opened 2021-07-01 10:00 UTC by Akalanka47000

Added events page with a search bar, filter options still left to implement
https://user-images.githubusercontent.com/73662613/124105670-156c7d80-da81-11eb-9c8e-f8437518c0ba.mp4

2021-07-01 16:27 UTC, sithumonline commented
@Akalanka47000 please provide screenshots

2021-07-01 16:41 UTC, LayanJay commented
This implementation is quite impressive. But the fact is it's not specified in the design document. If you like, let me know I can give you access to update the design document according to your implementation. 

And keep in mind before you start work on something, join the discussion, or assign yourself to the relevant issue(s). It will definitely save other members' time. 👍

2021-07-01 16:51 UTC, sithumonline requested changes
Rm gaps and unwanted comments

2021-07-01 16:51 UTC, sithumonline commented on components/Event.tsx
> +
Rm gaps between imports

2021-07-01 16:51 UTC, sithumonline commented on components/NavSearch.tsx
> +
Rm the gaps

2021-07-01 16:51 UTC, sithumonline commented on pages/events.tsx
> +// components
Rm gaps between imports

2021-07-01 16:58 UTC, sithumonline commented
@Akalanka47000 resolve conflicts and as @LayanJay mentioned, please assign yourself before the implementation.

2021-07-01 17:08 UTC, Shehanka commented
@sithumonline don't forget to use labels

2021-07-01 17:13 UTC, Shehanka commented
> This implementation is quite impressive. But the fact is it's not specified in the design document. If you like, let me know I can give you access to update the design document according to your implementation.
> 
> And keep in mind before you start work on something, join the discussion, or assign yourself to the relevant issue(s). It will definitely save other members' time. 👍

@sithumonline as I mentioned earlier assign issues to members, and also members can send a Draft(Work in Progress - WIP) PR too.

2021-07-02 17:36 UTC, sithumonline commented
@Akalanka47000 CI failed, Please remove `;` and remove unused `e`.

2021-07-03 15:11 UTC, closed without merging