Feature/clubs
sliit-foss/rsvp-frontend pull request #56
Opened 2021-07-12 13:30 UTC by MadhushaPrasad

![Capture](https://user-images.githubusercontent.com/50085447/125295560-f7393400-e342-11eb-9a15-3238cba569c3.PNG)

These missed elements were added

2021-07-12 13:48 UTC, sithumonline requested changes

2021-07-12 13:48 UTC, sithumonline commented on components/Navbar.tsx
> +                <Link href="/contactUs">
Uppercase for URL ??

2021-07-12 13:48 UTC, sithumonline commented on pages/clubs.tsx
> +import { HiArrowRight } from "react-icons/hi"
`" "` for imports ??

2021-07-12 13:48 UTC, sithumonline commented on tailwind.config.js
> +      gradientPurple: "#7B50A2",
`" "` ??

2021-07-14 10:01 UTC, Shehanka requested changes

2021-07-14 10:01 UTC, Shehanka commented on components/contactForm.tsx
> +export default ContactForm
make the file name start with capital

2021-07-14 10:03 UTC, Shehanka approved these changes

2021-07-14 10:04 UTC, merged